// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQPIeWNpIZjLD_QbKjmht-zSOc5uokcg0',
    appId: '1:1042588036995:web:ee1c0f92d22baea06110b6',
    messagingSenderId: '1042588036995',
    projectId: 'namaste-health-f49cf',
    authDomain: 'namaste-health-f49cf.firebaseapp.com',
    databaseURL: 'https://namaste-health-f49cf.firebaseio.com',
    storageBucket: 'namaste-health-f49cf.appspot.com',
    measurementId: 'G-RRNSVEBLJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnbhmn3Wb_T0oD8rWj2xKhSTzaPWdnYiE',
    appId: '1:1042588036995:android:9586a306dd29d3ea6110b6',
    messagingSenderId: '1042588036995',
    projectId: 'namaste-health-f49cf',
    databaseURL: 'https://namaste-health-f49cf.firebaseio.com',
    storageBucket: 'namaste-health-f49cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRsJtKqiNKRZ2ISXq4eT-yK4EJcTiNze4',
    appId: '1:1042588036995:ios:482e545c1d8458f06110b6',
    messagingSenderId: '1042588036995',
    projectId: 'namaste-health-f49cf',
    databaseURL: 'https://namaste-health-f49cf.firebaseio.com',
    storageBucket: 'namaste-health-f49cf.appspot.com',
    androidClientId: '1042588036995-1u59mk6ukdohksc9sb479codtg23t4bu.apps.googleusercontent.com',
    iosBundleId: 'com.example.callPoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRsJtKqiNKRZ2ISXq4eT-yK4EJcTiNze4',
    appId: '1:1042588036995:ios:c8773e77e3f5ebda6110b6',
    messagingSenderId: '1042588036995',
    projectId: 'namaste-health-f49cf',
    databaseURL: 'https://namaste-health-f49cf.firebaseio.com',
    storageBucket: 'namaste-health-f49cf.appspot.com',
    androidClientId: '1042588036995-1u59mk6ukdohksc9sb479codtg23t4bu.apps.googleusercontent.com',
    iosBundleId: 'com.example.callPoc.RunnerTests',
  );
}
